# Generated by Django 5.2.1 on 2025-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='alumnos_asignados',
            field=models.ManyToManyField(blank=True, related_name='talleres_asignados', to='cursos.alumno'),
        ),
    ]
