# Generated by Django 5.2.1 on 2025-05-21 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_taller_alumnos_asignados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='alumnos_asignados',
        ),
        migrations.AddField(
            model_name='taller',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
