# Generated by Django 5.2.1 on 2025-05-22 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('talleres', '0003_remove_taller_alumnos_asignados_taller_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='alumnos_asignados',
            field=models.ManyToManyField(blank=True, related_name='talleres_asignados', to='cursos.alumno'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
