# Generated by Django 5.2.1 on 2025-05-16 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporacion',
            name='clave_adicional',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='corporacion',
            name='contadoras',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'contadora'}, related_name='contadora_de', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporacion',
            name='coordinador',
            field=models.ForeignKey(limit_choices_to={'rol': 'coordinador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinador_de', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporacion',
            name='rut',
            field=models.CharField(default='000000000', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
