# Generated by Django 5.2.1 on 2025-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporaciones', '0002_corporacion_clave_adicional_corporacion_contadoras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporacion',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
