# Generated by Django 5.2.1 on 2025-05-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporaciones', '0003_alter_corporacion_rut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporacion',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corporacion',
            name='coordinador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'coordinador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinador_de', to=settings.AUTH_USER_MODEL),
        ),
    ]
