# Generated by Django 5.2.1 on 2025-05-07 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('corporacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colegios', to='corporaciones.corporacion')),
            ],
        ),
    ]
