# Generated by Django 5.2.1 on 2025-05-20 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='coordinador',
            field=models.ForeignKey(limit_choices_to={'rol': 'coordinador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegiados', to=settings.AUTH_USER_MODEL),
        ),
    ]
