# Generated by Django 5.2.1 on 2025-05-22 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0005_alter_colegio_coordinador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='coordinador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'coordinador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegio_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
