# Generated by Django 5.2.1 on 2025-05-08 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_initial'),
        ('cursos', '0001_initial'),
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.alumno')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.taller')),
            ],
        ),
    ]
